### 주문 요청
POST http://localhost:8080/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZXhwIjoxNzQ4MzMyNzI3fQ.dr5ZoEzthb8r3QhyNVPB60FPSs21jnKraiZXNLmprGY

{
  "items": [
    {
      "itemId": 2,
      "quantity": 2
    },
    {
      "itemId": 1,
      "quantity": 2
    }
  ]
}

### 주문 취소
DELETE http://localhost:8080/order/1/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZXhwIjoxNzQ4MzMxOTE3fQ.GNoj_iweAl0qKHcf0FMIvTvVVZa-XgvoOAcNbg2T5Uw
